version: '3'

services:
  postgres:
    image: postgres
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  index:
    image: opendatacube/wms:latest
    environment:
      # database
      - DB_HOSTNAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=postgres
      - DB_PORT=5432
      # index
      - WMS_CONFIG_PATH=/opt/config/wms/wms_cfg.py
      - WMS_CONFIG_URL="https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/master/dev/services/wms/ows/wms_cfg.py"
      - PRODUCT_URLS=https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/master/dev/products/hltc/hltc.yaml
      - DC_S3_INDEX_BUCKET=dea-public-data
      - DC_S3_INDEX_PREFIX=hltc
      - DC_S3_INDEX_SUFFIX=.yaml
      - DC_RANGES_PRODUCT=high_tide_comp_20p
      # AWS Configuration will be read from the local env var
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=ap-southeast-2
      - AWS_METADATA_SERVICE_TIMEOUT=60
      - AWS_METADATA_SERVICE_NUM_ATTEMPTS=30

    depends_on:
      - postgres
    command: bash -c "cd index; ./create-index.sh"
    volumes:
      - ./config:/opt/config/wms